services:
  - type: web
    name: portfolio-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    rootDir: backend
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        generateValue: true
        sync: false
